---
title: "Exercise 7 - Extra"
output:
---

```{r}
library(ggplot2)
library(ggsci)

library(rgl)
glplot3d = function (f, lims = c(-1,1,-1,1), nstep = 250) {
  
  stepx = (lims[2] - lims[1]) / nstep
  stepy = (lims[4] - lims[3]) / nstep
  
  x = seq(from = lims[1], to = lims[2], by = stepx)
  y = seq(from = lims[3], to = lims[4], by = stepy)
  z = matrix(nrow = length(x), ncol = length(y))
  
  for (i in 1:length(x)) {
    for (j in 1:length(y)) {
       z[i,j] = f(x[i], y[j])
    }
  }
  
  z[is.infinite(z)] = NaN # reduce infinite values to NaN for plot
  
  zlim = range(z, finite = TRUE)
  zlen = nstep + 1

  colorlut = heat.colors(zlen) # height color lookup table
  col = colorlut[round((z - zlim[1])/(zlim[2] - zlim[1]) * zlen) + 1] # assign colors to heights for each point

  persp3d(x, y, z, color = col, back = "filled")
}
```


*Problem 1*

(a)
```{r, fig.width=8, fig.height=3}
x = seq(from = 0.4, to = 10^-5, length.out = 100)

g = (x^3 + x^2 - 3*x - 2) / (2*x^2 - 1)

data = data.frame(x, g)

ggplot(data, aes(x = x, y = g)) +
  geom_line(linetype = "dashed") + geom_point(aes(color = g)) + scale_x_log10() +
  scale_colour_gradient(low = "dodgerblue", high="orangered3")
```

(b)
```{r, fig.width=8, fig.height=3}
x = seq(from = 0.4, to = 10^-5, length.out = 100)

g = (sqrt(1+x) - sqrt(1-x)) / (3*x)

data = data.frame(x, g)

ggplot(data, aes(x = x, y = g)) +
  geom_line(linetype = "dashed") + geom_point(aes(color = g)) + scale_x_log10() +
  scale_colour_gradient(low = "dodgerblue", high="orangered3") +
  geom_hline(yintercept = 1/3, linetype = "dotted")
```

(c)
```{r, fig.width=8, fig.height=3}
x = seq(from = 2, to = 1000, length.out = 100)

g = (3*x^2 - x - 2) / (x^2 - 1)

data = data.frame(x, g)

ggplot(data, aes(x = x, y = g)) +
  geom_line(linetype = "dashed") + geom_point(aes(color = g)) +
  scale_colour_gradient(low = "dodgerblue", high="orangered3")
```

(d)
```{r, fig.width=8, fig.height=3}
x = seq(from = 2, to = 1000, length.out = 100)

g = x * (sqrt(1+x^2) - x)

data = data.frame(x, g)

ggplot(data, aes(x = x, y = g)) +
  geom_line(linetype = "dashed") + geom_point(aes(color = g)) + scale_x_log10() +
  scale_colour_gradient(low = "dodgerblue", high="orangered3")
```

*Problem 2*

(a)
```{r}
f1 = function(x, y) {
  return( (y^2 * sin(2*x)) / (x^2 + 4) )
}

glplot3d(f1)
```

(b)
```{r}
f2 = function(x, y) return((y^2 - x^2)/(x^2 + y^2))

glplot3d(f2)
```

*Problem 3*

```{r}
f3 = function(x, y) {
  if (abs(x + y) < 10^-5) {
    return(0)
  } else {
    return((x^2 + y^2) / (x + y))
  }
}

glplot3d(f3)
```
